
using ResQLink.Data;
using ResQLink.Data.Entities;

// Ensure this code is inside a class, e.g., ResourceService
public class ResourceService
{
    public async Task<ResourceDistribution> CreateAllocationAndDistributionAsync(
        ResourceAllocation newAllocation,
        int evacueeId,
        int distributedByUserId,
        int quantity,
        AppDbContext db)
    {
        // Do NOT assign AllocationId on newAllocation
        db.ResourceAllocations.Add(newAllocation);
        await db.SaveChangesAsync(); // AllocationId is generated by DB

        var distribution = new ResourceDistribution
        {
            AllocationId = newAllocation.AllocationId,
            EvacueeId = evacueeId,
            DistributedByUserId = distributedByUserId,
            DistributedQuantity = quantity,
            DistributedAt = DateTime.UtcNow
        };

        db.ResourceDistributions.Add(distribution);
        await db.SaveChangesAsync();
        return distribution;
    }
}